### ISSUE TITLE
error logs

### ISSUE THREAD

**Issue by jayeola** [jayeola/puppet-vagrant#6]
what do i need to do?

==> puppet/masterhttp.log <==
[2016-09-19 14:22:35] ERROR OpenSSL::SSL::SSLError: SSL_accept SYSCALL returned=5 errno=0 state=SSLv2/v3 read client hello A
        /usr/share/ruby/vendor_ruby/puppet/network/http/webrick.rb:32:in `accept'
        /usr/share/ruby/vendor_ruby/puppet/network/http/webrick.rb:32:in `block (2 levels) in listen'
        /usr/share/ruby/webrick/server.rb:295:in `call'
        /usr/share/ruby/webrick/server.rb:295:in `block in start_thread'

**Comment by jayeola** [comment]
fixed
